### ISSUE TITLE
'numpy.float64' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by wwhhoo** [UCIDataLab/repeat-consumption#1]
My environment is ubuntu16.04 and use python2.
I try to run the Experiments.ipynb but got this error.

TypeError                                 Traceback (most recent call last)
<ipython-input-7-e3166cb23b97> in <module>()
      1 # dataset can be: 'go_sf', 'go_ny', 'tw_oc', 'tw_ny', 'lastfm', 'reddit_sample', 'reddit_top'
----> 2 mixture_model_results('go_sf')

<ipython-input-3-add98c0b5e8e> in mixture_model_results(dataset)
     10     print dataset
     11     train, val, test = get_dataset(dataset)
---> 12     train_mixture_model(train, val, test, dataset_name=dataset)
     13     train_mixture_model(train, val, test, dataset_name=dataset, method='recall')
     14     print

/home/james/James/repeat-consumption-master/models/mixture_model.py in train_mixture_model(train, val, test, method, recall_k, dataset_name, overwrite, num_proc)
     45         mix_weights = load_pickle(filename, False)
     46     else:
---> 47         train_matrix, global_matrix = get_train_global(train, val, test)
     48         components = [train_matrix, global_matrix]  # can add more components here
     49 

/home/james/James/repeat-consumption-master/models/mm_functions.py in get_train_global(train, val, test, is_eval)
     32     if is_eval:
     33         train = np.vstack((train, val))
---> 34     train_matrix = csr_matrix(_make_train(train, smooth_factor))
     35     glb_matrix = csr_matrix(_make_global(train_matrix, smooth_factor))
     36     return train_matrix, glb_matrix

/home/james/James/repeat-consumption-master/models/mm_functions.py in _make_train(data, smooth_factor)
     47         sparse matrix, that is normalized by row.
     48     """
---> 49     train_matrix = data_to_sparse(data).tolil()
     50     user_counts = np.array(train_matrix.sum(axis=1))[:, 0]
     51     train_matrix[np.where(user_counts == 0)] = smooth_factor

/home/james/James/repeat-consumption-master/util/array_util.py in data_to_sparse(data, shape, csc)
     24         data_matrix = coo_matrix((data[:, 2], (data[:, 0], data[:, 1])), shape=shape).tocsc()
     25     else:
---> 26         data_matrix = coo_matrix((data[:, 2], (data[:, 0], data[:, 1])), shape=shape).tocsr()
     27 
     28     data_matrix.eliminate_zeros()

/home/james/anaconda2/lib/python2.7/site-packages/scipy/sparse/coo.pyc in __init__(self, arg1, shape, dtype, copy)
    148                     M = np.max(row) + 1
    149                     N = np.max(col) + 1
--> 150                     self._shape = check_shape((M, N))
    151                 else:
    152                     # Use 2 steps to ensure shape has length 2.

/home/james/anaconda2/lib/python2.7/site-packages/scipy/sparse/sputils.pyc in check_shape(args, current_shape)
    279             new_shape = tuple(operator.index(arg) for arg in shape_iter)
    280     else:
--> 281         new_shape = tuple(operator.index(arg) for arg in args)
    282 
    283     if current_shape is None:

/home/james/anaconda2/lib/python2.7/site-packages/scipy/sparse/sputils.pyc in <genexpr>((arg,))
    279             new_shape = tuple(operator.index(arg) for arg in shape_iter)
    280     else:
--> 281         new_shape = tuple(operator.index(arg) for arg in args)
    282 
    283     if current_shape is None:

TypeError: 'numpy.float64' object cannot be interpreted as an index

And I also try to install numpy 1.11.0 but still not solved it.
Does anyone know what might be causing this problem?

**Comment by dkloz** [comment]
Try updating numpy. If that doesn't work, then simply change the data to be integers instead of float.
